In [1]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
import pandas as pd 
import numpy as np
from content_based_recemmendation.reccomend import Attraction_content_based
from collabrative_based_recemmendation.reccomend import Attractionrecemmond

c:\Users\S\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator TfidfTransformer from version 1.7.2 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\S\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator TfidfVectorizer from version 1.7.2 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [2]:
contentmodel=Attraction_content_based()
res_content=contentmodel.recommend("@@@Sacred::: Monkey Forest Sanctuary !!!!","douala")
res_content

,attraction,attractionaddress,ratingx
0,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5
1,Waterbom Bali,"Jl. Kartika Plaza, Kuta 80361 Indonesia",5
2,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia",5
3,Uluwatu Temple,"Jl. Raya Uluwatu Southern part of Bali, Pecatu...",5
4,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5

In [3]:
res_content["score"]=0.6*res_content.ratingx
res_content

,attraction,attractionaddress,ratingx,score
0,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5,3.0
1,Waterbom Bali,"Jl. Kartika Plaza, Kuta 80361 Indonesia",5,3.0
2,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia",5,3.0
3,Uluwatu Temple,"Jl. Raya Uluwatu Southern part of Bali, Pecatu...",5,3.0
4,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5,3.0

In [4]:
collabrativemodel=Attractionrecemmond()
res_collab=contentmodel.recommend("@@@Sacred::: Monkey Forest Sanctuary !!!!","douala")
res_collab

,attraction,attractionaddress,ratingx
0,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5
1,Waterbom Bali,"Jl. Kartika Plaza, Kuta 80361 Indonesia",5
2,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia",5
3,Uluwatu Temple,"Jl. Raya Uluwatu Southern part of Bali, Pecatu...",5
4,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5

In [5]:
res_collab["score"]=0.4*res_collab.ratingx
res_collab

,attraction,attractionaddress,ratingx,score
0,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5,2.0
1,Waterbom Bali,"Jl. Kartika Plaza, Kuta 80361 Indonesia",5,2.0
2,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia",5,2.0
3,Uluwatu Temple,"Jl. Raya Uluwatu Southern part of Bali, Pecatu...",5,2.0
4,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5,2.0

In [6]:
res_content.attraction

0    Tegalalang Rice Terrace
1              Waterbom Bali
2             Nusa Dua Beach
3             Uluwatu Temple
4    Tegalalang Rice Terrace
Name: attraction, dtype: object

In [7]:
list(res_collab.attraction)

['Tegalalang Rice Terrace',
 'Waterbom Bali',
 'Nusa Dua Beach',
 'Uluwatu Temple',
 'Tegalalang Rice Terrace']

In [8]:
combine=[]
for i in res_content.attraction:
    if i not in list(res_collab.attraction):
        combine.append(i)
combine.append(res_collab.attraction)
combine

[0    Tegalalang Rice Terrace
 1              Waterbom Bali
 2             Nusa Dua Beach
 3             Uluwatu Temple
 4    Tegalalang Rice Terrace
 Name: attraction, dtype: object]

In [9]:
hybrid=pd.concat([res_content,res_collab]).drop_duplicates(keep="first").reset_index(drop=True)
hybrid

,attraction,attractionaddress,ratingx,score
0,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5,3.0
1,Waterbom Bali,"Jl. Kartika Plaza, Kuta 80361 Indonesia",5,3.0
2,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia",5,3.0
3,Uluwatu Temple,"Jl. Raya Uluwatu Southern part of Bali, Pecatu...",5,3.0
4,Tegalalang Rice Terrace,"Jalan Raya Ceking, Tegalalang 80517 Indonesia",5,2.0
5,Waterbom Bali,"Jl. Kartika Plaza, Kuta 80361 Indonesia",5,2.0
6,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia",5,2.0
7,Uluwatu Temple,"Jl. Raya Uluwatu Southern part of Bali, Pecatu...",5,2.0

In [12]:
class Hybridmodel():
    def __init__(self,contentmodel,collabrativemodel):
        self.contentmodel=contentmodel
        self.collabrativemodel=collabrativemodel
        
    def reccomend(self,desc,attractioncity):
        res_content=self.contentmodel.recommend(desc,attractioncity)
        res_collab=self.collabrativemodel.recemmond(desc,attractioncity)
        res_content["score"]=0.6*res_content.ratingx
        res_collab["score"]=0.4*res_collab.ratingx
        result=pd.concat([res_content,res_collab]).drop_duplicates(keep="first").reset_index(drop=True).sort_values(ascending=False,by="score")
        result.drop(["score"],inplace=True,axis=1)
        return result

In [13]:
model=Hybridmodel(contentmodel,collabrativemodel)
print(model.reccomend("@@@Sacred Monkey Forest Sanctuary !!!!","douala"))

                attraction                                  attractionaddress  \
0  Tegalalang Rice Terrace      Jalan Raya Ceking, Tegalalang 80517 Indonesia
1            Waterbom Bali            Jl. Kartika Plaza, Kuta 80361 Indonesia
2           Nusa Dua Beach     Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia
3           Uluwatu Temple  Jl. Raya Uluwatu Southern part of Bali, Pecatu...
4  Tegalalang Rice Terrace      Jalan Raya Ceking, Tegalalang 80517 Indonesia
5            Waterbom Bali            Jl. Kartika Plaza, Kuta 80361 Indonesia
6           Uluwatu Temple  Jl. Raya Uluwatu Southern part of Bali, Pecatu...
7     Tegenungan Waterfall  Jl. Raya Tegenungan, Kemenuh, Ubud 80581 Indon...
8         Tanah Lot Temple  Kecamatan Kediri, Kabupaten Tabanan, Beraban 8...

   ratingx
0        5
1        5
2        5
3        5
4        5
5        5
6        5
7        5
8        3